Repository aismam/ScalaTowerDefense, pull requests merged in 2022-06, with the labels that each got.

#42 Refactoring grid tile
  app/build.gradle.kts
  app/src/main/resources/DefaultPaths/HardPath.json
  app/src/main/resources/DefaultPaths/NormalPath.json
  app/src/main/resources/DefaultPaths/SimplePath.json
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/DrawingManager.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/GridController.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/Wave.scala
  app/src/main/scala/Model/Enemy/WaveImpl.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/main/scala/Model/Grid/PathMaker.scala
  app/src/main/scala/Model/Grid/Tile.scala
  app/src/main/scala/Utility/SimplePathJsonObject.java
  app/src/main/scala/Utility/Utils.scala
  app/src/main/scala/ViewTMP/GameView.scala
  app/src/test/scala/Enemy/EnemyTest.scala
  app/src/test/scala/ScalaTowerDefense/UtilitiesTest.scala
Labels: enhancement, Upgrade

#49 Wave scheduler
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/EnemyType.scala
  app/src/main/scala/Model/Enemy/Wave.scala
  app/src/main/scala/Model/Enemy/WaveImpl.scala
  app/src/test/scala/Enemy/EnemyTest.scala
Labels: bug, enhancement

#56 Added first part of path chooser and fixed path selection
  app/src/main/resources/DefaultPaths/HardPath.json
  app/src/main/resources/DefaultPaths/NormalPath.json
  app/src/main/resources/DefaultPaths/SimplePath.json
  app/src/main/scala/Cache/TowerDefenseCache.scala
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/GridController.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/WaveScheduler.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/main/scala/Model/Grid/PathMaker.scala
  app/src/main/scala/Utility/RandomName.scala
  app/src/main/scala/View/EventHandlers/GameEventHandlers.scala
  app/src/main/scala/View/EventHandlers/MainMenuEventHandlers.scala
  app/src/main/scala/View/ModelView/MainMenuViewModel.scala
  app/src/main/scala/View/ViewController/GameViewController.scala
  app/src/main/scala/View/ViewController/MainMenuViewController.scala
  app/src/main/scala/View/ViewModel/GameViewModel.scala
  app/src/main/scala/View/ViewModel/MainMenuViewModel.scala
  app/src/test/scala/Grid/GridTest.scala
Labels: enhancement, test

#55 Implement tower shoot
  app/src/main/resources/application.properties
  app/src/main/resources/projectiles/cannon_projectile.png
  app/src/main/resources/projectiles/flame_projectile.png
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/DrawingManager.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/Tower/Tower.scala
  app/src/main/scala/Model/Enemy/WaveScheduler.scala
  app/src/main/scala/Model/Projectile/CannonProjectile.scala
  app/src/main/scala/Model/Projectile/Exceptions/ProjectileTypeNotExistException.scala
  app/src/main/scala/Model/Projectile/Projectile.scala
  app/src/main/scala/Model/Projectile/ProjectileFactory.scala
  app/src/main/scala/Model/Projectile/ProjectileType.scala
  app/src/main/scala/Model/Projectile/ProjectileTypes.scala
  app/src/main/scala/Model/Tower/BaseTower.scala
  app/src/main/scala/Model/Tower/CannonTower.scala
  app/src/main/scala/Model/Tower/CircularRadiusTower.scala
  app/src/main/scala/Model/Tower/FlameTower.scala
  app/src/main/scala/Model/Tower/ShooterTower.scala
  app/src/main/scala/Model/Tower/TowerType.scala
  app/src/main/scala/Model/Tower/TowerTypes.scala
  app/src/main/scala/Utility/Utils.scala
  app/src/main/scala/Utility/WayPoint.scala
  app/src/test/scala/Tower/TowerGenerationTest.scala
Labels: bug, enhancement

#58 Wave and enemies update
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Model/Enemy/Enemy.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/EnemyType.scala
  app/src/main/scala/Model/Enemy/WaveScheduler.scala
  app/src/test/scala/Enemy/EnemyTest.scala
Labels: bug

#61 Fix tower and projectile paramenters and some refactor
  app/src/main/resources/log4j2.properties
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/Tower/Tower.scala
  app/src/main/scala/Model/Projectile/CannonProjectile.scala
  app/src/main/scala/Model/Projectile/Projectile.scala
  app/src/main/scala/Model/Projectile/ProjectileFactory.scala
  app/src/main/scala/Model/Projectile/ProjectileType.scala
  app/src/main/scala/Model/Tower/BaseTower.scala
  app/src/main/scala/Model/Tower/CannonTower.scala
  app/src/main/scala/Model/Tower/CircularRadiusTower.scala
  app/src/main/scala/Model/Tower/FlameTower.scala
  app/src/main/scala/Model/Tower/ShooterTower.scala
  app/src/main/scala/Model/Tower/TowerType.scala
  app/src/test/scala/Controller/GameControllerTest.scala
  app/src/test/scala/Tower/TowerGenerationTest.scala
  app/src/test/scala/Tower/TowerShootTest.scala
Labels: enhancement

#68 Fix file path reader
  app/src/main/scala/Utility/Utils.scala
Labels: bug

#70 Drawing fix
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/DrawingManager.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/GridController.scala
  app/src/main/scala/Controller/Tower/Tower.scala
  app/src/main/scala/Controller/UpdateManager.scala
  app/src/main/scala/Model/Enemy/Enemy.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/WaveScheduler.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/main/scala/Model/Grid/PathMaker.scala
  app/src/main/scala/Model/Grid/Tile.scala
  app/src/main/scala/Model/Projectile/Projectile.scala
  app/src/main/scala/Model/Tower/ShooterTower.scala
  app/src/main/scala/Utility/Utils.scala
  app/src/main/scala/View/EventHandlers/GameEventHandlers.scala
  app/src/main/scala/View/EventHandlers/MainMenuEventHandlers.scala
  app/src/main/scala/View/MusicPlayer.scala
  app/src/main/scala/View/ViewController/GameViewController.scala
  app/src/main/scala/View/ViewController/MainMenuViewController.scala
  app/src/main/scala/View/ViewModel/GameViewModel.scala
  app/src/test/scala/Grid/GridTest.scala
  app/src/test/scala/Utility/UtilsTest.scala
Labels: duplicate, help wanted, Upgrade

#75 Player health money label
  app/src/main/resources/DefaultPaths/HardPath.json
  app/src/main/scala/Controller/UpdateManager.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/test/scala/Grid/GridTest.scala
Labels: enhancement

#77 Restart game
  app/src/main/resources/enemies/baseEnemy.png
  app/src/main/resources/enemies/enemy.jpg
  app/src/main/resources/enemies/enemy.png
  app/src/main/resources/enemies/mediumEnemy.png
  app/src/main/resources/enemies/superEnemy.png
  app/src/main/resources/towers/base_tower.png
  app/src/main/resources/towers/cannon_tower.png
  app/src/main/resources/towers/flame_tower.png
  app/src/main/scala/Cache/TowerDefenseCache.scala
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/GridController.scala
  app/src/main/scala/Controller/Wave/Wave.scala
  app/src/main/scala/Controller/Wave/WaveImpl.scala
  app/src/main/scala/Controller/WaveScheduler.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/main/scala/Model/Grid/GridController.scala
  app/src/main/scala/Model/Grid/PathMaker.scala
  app/src/main/scala/Model/Grid/Tile.scala
  app/src/main/scala/Model/Grid/Tiles/EndTile.scala
  app/src/main/scala/Model/Grid/Tiles/Grass.scala
  app/src/main/scala/Model/Grid/Tiles/Nothing.scala
  app/src/main/scala/Model/Grid/Tiles/Path.scala
  app/src/main/scala/Model/Grid/Tiles/StartTile.scala
  app/src/main/scala/Model/Grid/Tiles/TileType.scala
  app/src/main/scala/Utility/Utils.scala
  app/src/main/scala/View/EventHandlers/GameEventHandlers.scala
  app/src/main/scala/View/EventHandlers/MainMenuEventHandlers.scala
  app/src/main/scala/View/ViewController/GameViewController.scala
  app/src/test/scala/Enemy/EnemyTest.scala
  app/src/test/scala/Grid/GridTest.scala
Labels: documentation, enhancement, Upgrade

#81 Refactor enemy and wave
  app/src/main/scala/Configuration/DefaultConfig.scala
  app/src/main/scala/Controller/GameController.scala
  app/src/main/scala/Controller/UpdateManager.scala
  app/src/main/scala/Controller/Wave/Wave.scala
  app/src/main/scala/Controller/Wave/WaveImpl.scala
  app/src/main/scala/Controller/WaveScheduler.scala
  app/src/main/scala/Model/Enemy/Easy.scala
  app/src/main/scala/Model/Enemy/Enemy.scala
  app/src/main/scala/Model/Enemy/EnemyImpl.scala
  app/src/main/scala/Model/Enemy/EnemyType.scala
  app/src/main/scala/Model/Enemy/Hard.scala
  app/src/main/scala/Model/Enemy/Medium.scala
  app/src/main/scala/View/MusicPlayer.scala
  app/src/main/scala/View/ViewController/GameViewController.scala
  app/src/test/scala/Controller/GameControllerTest.scala
  app/src/test/scala/Enemy/EnemyTest.scala
  app/src/test/scala/Enemy/EnemyWaveTest.scala
  app/src/test/scala/Tower/TowerShootTest.scala
Labels: enhancement, help wanted

#87 fixed the grid model dependencies
  app/src/main/scala/Model/Enemy/Enemy.scala
  app/src/main/scala/Model/Grid/Grid.scala
  app/src/main/scala/Model/Grid/GridController.scala
  app/src/main/scala/Model/Grid/PathMaker.scala
  app/src/main/scala/Model/Grid/Tile.scala
  app/src/main/scala/Model/Player.scala
  app/src/main/scala/View/EventHandlers/GameEventHandlers.scala
  app/src/main/scala/View/EventHandlers/MainMenuEventHandlers.scala
  app/src/main/scala/View/ViewController/GameViewController.scala
  app/src/main/scala/View/ViewController/MainMenuViewController.scala
  app/src/main/scala/View/ViewModel/GameViewModel.scala
  app/src/main/scala/View/ViewModel/MainMenuViewModel.scala
  app/src/test/scala/Grid/GridTest.scala
Labels: documentation, duplicate, Upgrade

#71 Report
  report/00_introduction.md
  report/01_process.md
  report/02_requisiti.md
  report/03_design.md
  report/04_implementation.md
  report/05_comments.md
  report/images/application-flow-chart.jpg
  report/images/initial_diagram.jpg
  report/images/package_organization.jpg
  report/images/tower_selection-creation.jpg
  report/images/use_case_diagram.jpg
Labels: documentation
